---
title: ""
author: "Cade Jeong"
date: '2022-11-17'
output: html_document
---

```{r echo=FALSE, eval=TRUE, message=FALSE}
source("../source/a4-helpers.R")
source("../source/analysis.R")
```

## Abstract 
With the ever increasing population in prison and the rate of incarceration in America, we are greatly concerned about the life of those behind bars and the possible racial disparities that exist regarding the population in prison. Our goal is to find where these disparities exist using data and suggest ways to fix them.


## Introduction 
Ever since 1865 with the end of the Civil War and the passage of the 13th Amendment, the incarceration and arrests had been a major issue to those who are Black and/or not privileged. 
And as if to follow the historical trend, newly elected officials and policymaker did not step up 
to address the issues at hand but rather, caused more suffering. Although the idea of racial disparities within the jail population is a big issue itself, within the context that the U.S. holds 16% of the jail population in the entire world is more troublesome. As quoted from [Vera Institute](https://www.vera.org/), “From 1850 to 1940, racial and ethnic minorities—including foreign-born and non-English speaking European immigrants—made up 40 to 50 percent of the prison population. In 2015, about 55 percent of people imprisoned in federal or state prisons were Black or Latino.” The dataset is collected so that we can analyze the patterns in which inequalities exist and suggest possible solutions to how they can be fixed. Which makes the direct stakeholders for this dataset and its usage being policymakers, families (including self) of those being incarcerated, researchers (data), and indirect being all those who belong in the privilege hazard; not knowing about what is going on. 


## Data Summary 

